/**
 * WCAG contrast audit of the design tokens.
 *
 * Automated accessibility testing cannot check colour contrast in a test
 * environment that never paints, so this checks the palette at the source
 * instead: every semantic pair, in light and dark, across every theme preset.
 *
 *   pnpm audit:contrast
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { contrastRatio, resolveColour } from "./colour";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const themesSrc = join(repoRoot, "packages", "themes", "src");

/** WCAG 2.2 AA: normal text. */
const TEXT_MINIMUM = 4.5;
/** WCAG 2.2 AA: large text, and non-text UI such as borders and focus rings. */
const UI_MINIMUM = 3;

interface Pair {
  label: string;
  foreground: string;
  background: string;
  minimum: number;
  /**
   * Advisory pairs are reported but do not fail.
   *
   * WCAG 1.4.11 covers what is needed to *identify* a component or its state.
   * A divider or a card outline is structural decoration — the content inside
   * is already distinguishable without it — so holding those to 3:1 would mean
   * heavy rules everywhere in the name of a rule that does not apply. An input
   * border is different: the field's background matches the page, so the border
   * is the only thing saying it is a field.
   */
  advisory?: boolean;
}

/**
 * The pairs that actually appear on screen.
 *
 * Written out rather than generated by matching `*-foreground` names: several
 * tokens are used against a surface they are not named after — muted-foreground
 * is read on the page background far more often than on `muted`.
 */
const PAIRS: Pair[] = [
  {
    label: "foreground on background",
    foreground: "foreground",
    background: "background",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "muted-foreground on background",
    foreground: "muted-foreground",
    background: "background",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "muted-foreground on card",
    foreground: "muted-foreground",
    background: "card",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "muted-foreground on muted",
    foreground: "muted-foreground",
    background: "muted",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "card-foreground on card",
    foreground: "card-foreground",
    background: "card",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "popover-foreground on popover",
    foreground: "popover-foreground",
    background: "popover",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "primary-foreground on primary",
    foreground: "primary-foreground",
    background: "primary",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "primary-foreground on primary-hover",
    foreground: "primary-foreground",
    background: "primary-hover",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "secondary-foreground on secondary",
    foreground: "secondary-foreground",
    background: "secondary",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "accent-foreground on accent",
    foreground: "accent-foreground",
    background: "accent",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "destructive-foreground on destructive",
    foreground: "destructive-foreground",
    background: "destructive",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "success-foreground on success",
    foreground: "success-foreground",
    background: "success",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "warning-foreground on warning",
    foreground: "warning-foreground",
    background: "warning",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "info-foreground on info",
    foreground: "info-foreground",
    background: "info",
    minimum: TEXT_MINIMUM,
  },
  // Coloured text on a plain surface: badges, alert titles, destructive links.
  {
    label: "destructive on background",
    foreground: "destructive",
    background: "background",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "success on background",
    foreground: "success",
    background: "background",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "warning on background",
    foreground: "warning",
    background: "background",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "info on background",
    foreground: "info",
    background: "background",
    minimum: TEXT_MINIMUM,
  },
  {
    label: "primary on background",
    foreground: "primary",
    background: "background",
    minimum: TEXT_MINIMUM,
  },
  // Non-text: borders, inputs, focus rings.
  {
    label: "border on background",
    foreground: "border",
    background: "background",
    minimum: UI_MINIMUM,
    advisory: true,
  },
  {
    label: "border-strong on background",
    foreground: "border-strong",
    background: "background",
    minimum: UI_MINIMUM,
    advisory: true,
  },
  {
    label: "input on background",
    foreground: "input",
    background: "background",
    minimum: UI_MINIMUM,
  },
  {
    label: "ring on background",
    foreground: "ring",
    background: "background",
    minimum: UI_MINIMUM,
  },
];

type Tokens = Map<string, string>;

/** Every `--name: value;` declaration inside the given selector block. */
function readBlock(css: string, selector: string): Tokens {
  const tokens: Tokens = new Map();
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const block = new RegExp(`${escaped}\\s*\\{([\\s\\S]*?)\\n\\}`).exec(css);
  if (!block?.[1]) return tokens;

  for (const declaration of block[1].matchAll(/--([\w-]+):\s*([^;]+);/g)) {
    if (declaration[1] && declaration[2]) tokens.set(declaration[1], declaration[2].trim());
  }
  return tokens;
}

/** Follows `var(--x)` chains to a literal colour. */
function resolveToken(
  name: string,
  scales: Tokens,
  semantic: Tokens,
  seen = new Set<string>(),
): string | undefined {
  if (seen.has(name)) return undefined;
  seen.add(name);

  const value = semantic.get(name) ?? scales.get(`color-${name}`) ?? scales.get(name);
  if (!value) return undefined;

  const reference = /^var\(--([\w-]+)\)$/.exec(value);
  if (reference?.[1]) return resolveToken(reference[1], scales, semantic, seen);
  return value;
}

interface Finding {
  theme: string;
  mode: string;
  pair: string;
  ratio: number;
  minimum: number;
  advisory: boolean;
}

function auditScheme(theme: string, mode: string, scales: Tokens, semantic: Tokens): Finding[] {
  const findings: Finding[] = [];

  for (const pair of PAIRS) {
    const backgroundValue = resolveToken(pair.background, scales, semantic);
    const foregroundValue = resolveToken(pair.foreground, scales, semantic);
    if (!backgroundValue || !foregroundValue) continue;

    // The page background is opaque, so a translucent token composites over it.
    const pageValue = resolveToken("background", scales, semantic);
    const page = pageValue ? resolveColour(pageValue) : undefined;

    const background = resolveColour(backgroundValue, page);
    const foreground = resolveColour(foregroundValue, background ?? page);
    if (!background || !foreground) continue;

    const ratio = contrastRatio(foreground, background);
    if (ratio + 0.005 < pair.minimum) {
      findings.push({
        theme,
        mode,
        pair: pair.label,
        ratio,
        minimum: pair.minimum,
        advisory: pair.advisory ?? false,
      });
    }
  }

  return findings;
}

const tokensCss = readFileSync(join(themesSrc, "tokens.css"), "utf8");
const baseCss = readFileSync(join(themesSrc, "base.css"), "utf8");

const scales = readBlock(tokensCss, "@theme");
const light = readBlock(baseCss, ":root");
const dark = readBlock(baseCss, ".dark");

const findings: Finding[] = [
  ...auditScheme("default", "light", scales, light),
  ...auditScheme("default", "dark", scales, dark),
];

const presets = ["ocean", "emerald", "violet", "rose", "amber", "monochrome"];
for (const preset of presets) {
  const css = readFileSync(join(themesSrc, "presets", `${preset}.css`), "utf8");
  findings.push(
    ...auditScheme(
      preset,
      "light",
      scales,
      new Map([...light, ...readBlock(css, `[data-theme="${preset}"]`)]),
    ),
    ...auditScheme(
      preset,
      "dark",
      scales,
      new Map([...dark, ...readBlock(css, `.dark[data-theme="${preset}"]`)]),
    ),
  );
}

const schemes = 2 + presets.length * 2;
const checks = schemes * PAIRS.length;

const failures = findings.filter((finding) => !finding.advisory);
const advisories = findings.filter((finding) => finding.advisory);

function report(entries: Finding[]) {
  for (const finding of entries) {
    console.log(
      `  ${finding.theme}/${finding.mode}`.padEnd(24) +
        finding.pair.padEnd(42) +
        `${finding.ratio.toFixed(2)}:1  (target ${String(finding.minimum)}:1)`,
    );
  }
}

if (advisories.length > 0) {
  console.log(
    `Advisory — structural, not required by WCAG 1.4.11 (${String(advisories.length)}):\n`,
  );
  // Deduplicated: the same neutral pair repeats across every preset.
  const seen = new Set<string>();
  report(
    advisories.filter((finding) => {
      const key = `${finding.mode}:${finding.pair}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    }),
  );
  console.log("");
}

if (failures.length === 0) {
  console.log(
    `Contrast: ${String(checks)} pairs across ${String(schemes)} schemes, all required pairs pass.`,
  );
  process.exit(0);
}

console.error(
  `Contrast: ${String(failures.length)} of ${String(checks)} required pairs fail.\n`,
);
report(failures);
process.exit(1);
