import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Prepares everything the docs site serves from other packages.
 *
 * Two jobs, both about not keeping a second copy of anything:
 *
 * 1. Publishes the registry the CLI reads. The docs site is the registry's
 *    host, so `public/r` is a copy of what `@dowel-ui/registry` just built —
 *    never hand-maintained.
 * 2. Generates static imports for every Storybook story, so the previews on a
 *    component's page are literally the stories that are tested in CI. There is
 *    no second set of examples to drift.
 */

const here = dirname(fileURLToPath(import.meta.url));
const docsRoot = join(here, "..");
const repoRoot = join(docsRoot, "..", "..");
const registryDir = join(repoRoot, "packages", "registry", "r");
const componentsDir = join(repoRoot, "packages", "ui", "src", "components");
const blocksDir = join(repoRoot, "packages", "ui", "src", "blocks");

/** Newest modification time anywhere under a directory. */
function newestMtime(directory: string): number {
  let newest = 0;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    const mtime = entry.isDirectory() ? newestMtime(path) : statSync(path).mtimeMs;
    if (mtime > newest) newest = mtime;
  }
  return newest;
}

function publishRegistry(): number {
  const index = join(registryDir, "index.json");

  if (!existsSync(index)) {
    throw new Error(
      `No registry at ${registryDir}. Run \`pnpm --filter @dowel-ui/registry build\` first.`,
    );
  }

  // Turbo's dependency graph rebuilds the registry before this runs, but a bare
  // `next build` does not — and publishing a stale registry means the site
  // documents, and the CLI installs, code that no longer exists. Better to stop
  // than to serve something that looks right.
  if (newestMtime(componentsDir) > statSync(index).mtimeMs) {
    throw new Error(
      "The registry is older than the component sources it was generated from.\n" +
        "Run `pnpm --filter @dowel-ui/registry build` (or build through turbo, which does it for you).",
    );
  }

  const target = join(docsRoot, "public", "r");
  rmSync(target, { recursive: true, force: true });
  mkdirSync(target, { recursive: true });
  cpSync(registryDir, target, { recursive: true });

  return readdirSync(target).length;
}

function identifier(name: string): string {
  const [first, ...rest] = name.split("-");
  return `${first ?? ""}${rest.map((part) => part[0]?.toUpperCase() + part.slice(1)).join("")}Stories`;
}

interface PreviewSource {
  name: string;
  /** Import path segment: "components" or "blocks". */
  group: string;
}

function storiesIn(directory: string, group: string): PreviewSource[] {
  if (!existsSync(directory)) return [];

  return readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => existsSync(join(directory, name, `${name}.stories.tsx`)))
    .sort()
    .map((name) => ({ name, group }));
}

function generatePreviews(): number {
  // Registry names are unique across components and blocks, so one flat map
  // serves both — the integrity test enforces that uniqueness.
  const sources = [
    ...storiesIn(componentsDir, "components"),
    ...storiesIn(blocksDir, "blocks"),
  ];

  const imports = sources
    .map(
      (source) =>
        `import * as ${identifier(source.name)} from "@ui/${source.group}/${source.name}/${source.name}.stories";`,
    )
    .join("\n");

  const entries = sources
    .map((source) => `  "${source.name}": ${identifier(source.name)},`)
    .join("\n");

  writeFileSync(
    join(docsRoot, "src", "lib", "previews.generated.ts"),
    `// Generated by scripts/prepare.ts. Do not edit.
//
// Static imports rather than a glob, because Next resolves imports at build
// time and a dynamic path would defeat both bundling and type checking.
import type { StoryModule } from "./story-types";

${imports}

export const storyModules: Record<string, StoryModule> = {
${entries}
};
`,
  );

  return sources.length;
}

const files = publishRegistry();
const previews = generatePreviews();

console.log(
  `Prepared docs: ${String(files)} registry files published, ${String(previews)} preview modules generated.`,
);
