import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { createElement, Fragment, type ReactNode } from "react";
import { renderToStaticMarkup } from "react-dom/server";

import { asStory, asStoryMeta, type StoryArgs, type StoryModule } from "../src/lib/story-types";
import { exportOrder } from "./stories";

/**
 * Renders a licensed block's stories to static HTML, at build time.
 *
 * A live preview is a React component running in the browser, and a React
 * component running in the browser is its own source in a chunk anyone can
 * download. That is precisely how the paid catalogue was readable from the
 * documentation site: `previews.generated.ts` imported every block, so every
 * page carrying a preview shipped all four Pro blocks — including the pages of
 * free components, which have nothing to do with them.
 *
 * The answer is not to hide the preview. An unseen block is an unsold block,
 * and the registry already withholds the file itself. What the site owes a
 * visitor is a true picture of what they would be buying, which is what this
 * produces: the same story the tests run, rendered here, delivered as markup.
 * A picture of the block rather than the block.
 *
 * Run as its own process, with `packages/ui` as the working directory. tsx
 * takes its JSX setting from the tsconfig it finds there, and the docs app's
 * says `preserve` for Next's benefit — under which tsx emits calls to the
 * classic runtime that these files, written for the automatic one, never
 * import. The block sources are `packages/ui` files and are compiled by the
 * config that governs them.
 */

const here = dirname(fileURLToPath(import.meta.url));
const docsRoot = join(here, "..");
const repoRoot = join(docsRoot, "..", "..");
const blocksDir = join(repoRoot, "packages", "ui", "src", "blocks");
const outFile = join(docsRoot, "src", "lib", "pro-previews.generated.ts");

interface RenderedStory {
  name: string;
  html: string;
}

async function renderStories(name: string): Promise<RenderedStory[]> {
  const file = join(blocksDir, name, `${name}.stories.tsx`);

  // By file URL rather than by module specifier: the alias that resolves
  // `@ui/...` belongs to the docs app's tsconfig, and this runs under the
  // component package's.
  const storyModule = (await import(pathToFileURL(file).href)) as StoryModule;

  const meta = asStoryMeta(storyModule.default);
  if (!meta) {
    throw new Error(`${name} has no story meta, so there is nothing to render.`);
  }

  const rendered: RenderedStory[] = [];

  // Source order, for the same reason the live previews use it: the first story
  // is the canonical one, and a module namespace object sorts its own keys.
  for (const storyName of exportOrder(file)) {
    const story = asStory(storyModule[storyName]);
    if (!story) continue;

    const Render = story.render ?? meta.render ?? meta.component;
    if (!Render) continue;

    const args: StoryArgs = { ...meta.args, ...story.args };

    // Rendered as a component rather than called as a function, because stories
    // use hooks — the same reason StoryPreview does it this way.
    let node: ReactNode = createElement(Render, args);
    for (const decorator of meta.decorators) {
      const current = node;
      const Wrapped = () => createElement(Fragment, null, current);
      node = decorator(Wrapped, { args, globals: {}, parameters: {} });
    }

    rendered.push({
      name: storyName,
      // Namespaced ids. This markup is injected into a page React also renders,
      // and two independent renders both start counting from zero — without a
      // prefix, the block's ids and the page's collide.
      html: renderToStaticMarkup(node, {
        identifierPrefix: `${name}-${storyName}-`,
      }),
    });
  }

  if (rendered.length === 0) {
    throw new Error(`${name} produced no previews, so its page would show nothing.`);
  }

  return rendered;
}

/** Renders the named blocks and writes the module the site reads. */
export async function writeProPreviews(names: string[]): Promise<number> {
  const previews: Record<string, RenderedStory[]> = {};

  for (const name of [...names].sort()) {
    previews[name] = await renderStories(name);
  }

  writeFileSync(
    outFile,
    `// Generated by scripts/prerender.ts. Do not edit.
//
// Licensed blocks, rendered to markup at build time so the browser never
// receives their code. Every other preview on the site is live; these are
// stills, because a live one is a copy of the source in a public chunk.
export interface ProPreviewStory {
  /** The story's export name, shown on the switcher. */
  name: string;
  /** Its rendered markup, with ids namespaced to the block. */
  html: string;
}

export const proPreviews: Record<string, ProPreviewStory[]> = ${JSON.stringify(previews, null, 2)};
`,
  );

  return Object.values(previews).reduce((total, stories) => total + stories.length, 0);
}

// Invoked by scripts/prepare.ts with the licensed names, which it already knows
// from the registry build. Reading them again here would be a second answer to
// a question that must only have one.
const names = process.argv.slice(2);
if (names.length === 0) {
  throw new Error("No licensed blocks were named, so there is nothing to prerender.");
}

const count = await writeProPreviews(names);
console.log(
  `Prerendered ${String(count)} previews for ${String(names.length)} licensed blocks.`,
);
