import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it } from "vitest";

import { expectNoA11yViolations } from "../../../test/a11y";
import { AIDisclosure, AIDisclosureProvenance, type DisclosureKind } from "./ai-disclosure";

const KINDS: DisclosureKind[] = ["interaction", "generated", "manipulated", "assisted"];

describe("AIDisclosure", () => {
  it("says what it means in words", () => {
    render(<AIDisclosure kind="generated" />);
    expect(screen.getByText("Generated by AI")).toBeInTheDocument();
  });

  it.each(KINDS)("gives %s a default of its own", (kind) => {
    const { container } = render(<AIDisclosure kind={kind} />);
    expect(container.textContent?.trim().length ?? 0).toBeGreaterThan(0);
  });

  it("gives every kind a different default", () => {
    // Four situations that mean different things to a reader; one shared
    // sentence would collapse the distinction the kinds exist to draw.
    const labels = KINDS.map((kind) => {
      const { container, unmount } = render(<AIDisclosure kind={kind} />);
      const text = container.textContent ?? "";
      unmount();
      return text;
    });

    expect(new Set(labels).size).toBe(KINDS.length);
  });

  it("distinguishes assisted from generated, which the Act treats differently", () => {
    const { container: assisted } = render(<AIDisclosure kind="assisted" />);
    expect(assisted.textContent).toMatch(/reviewed by a person/i);
  });

  it("takes wording of your own", () => {
    render(<AIDisclosure kind="interaction" label="You're talking to Ada, our bot" />);

    expect(screen.getByText("You're talking to Ada, our bot")).toBeInTheDocument();
    expect(screen.queryByText("You are chatting with an AI assistant")).not.toBeInTheDocument();
  });

  it("exposes the kind for styling without it carrying the meaning", () => {
    const { container } = render(<AIDisclosure kind="manipulated" />);
    expect(container.querySelector("[data-slot='ai-disclosure']")).toHaveAttribute(
      "data-kind",
      "manipulated",
    );
  });

  describe("the icon is decoration, never the disclosure", () => {
    it("hides the default mark from assistive technology", () => {
      // A sparkle a screen reader skips is not a notice.
      const { container } = render(<AIDisclosure kind="generated" />);
      expect(container.querySelector("svg")).toHaveAttribute("aria-hidden", "true");
    });

    it("still carries the text when a caller supplies their own mark", () => {
      render(<AIDisclosure kind="generated" icon={<span data-testid="eu-icon" />} />);

      expect(screen.getByTestId("eu-icon")).toBeInTheDocument();
      expect(screen.getByText("Generated by AI")).toBeInTheDocument();
    });

    it("ships no official mark of its own", () => {
      // The Commission's icons are free to use but deliberately not bundled:
      // an official mark inside a library ends up on content nobody checked.
      const { container } = render(<AIDisclosure kind="generated" />);
      expect(container.querySelectorAll("img")).toHaveLength(0);
    });
  });

  it.each(["inline", "banner", "overlay"] as const)("renders the %s variant", (variant) => {
    const { container } = render(<AIDisclosure kind="generated" variant={variant} />);
    expect(container.querySelector("[data-slot='ai-disclosure']")).toBeInTheDocument();
  });

  it("merges a caller's className rather than dropping it", () => {
    const { container } = render(<AIDisclosure kind="generated" className="mt-4" />);
    expect(container.querySelector("[data-slot='ai-disclosure']")).toHaveClass("mt-4");
  });

  it("has no accessibility violations", async () => {
    const { container } = render(<AIDisclosure kind="interaction" variant="banner" />);
    await expectNoA11yViolations(container);
  });
});

describe("AIDisclosureProvenance", () => {
  const claims = [
    { label: "Model", value: "Acme Diffusion 3" },
    { label: "Created", value: "3 September 2026" },
  ];

  it("shows the claims behind the label", async () => {
    const user = userEvent.setup();
    render(<AIDisclosureProvenance claims={claims} />);

    await user.click(screen.getByRole("button", { name: "Content details" }));

    expect(screen.getByText("Model")).toBeInTheDocument();
    expect(screen.getByText("Acme Diffusion 3")).toBeInTheDocument();
  });

  describe("claims are not findings", () => {
    it("says nobody checked when nobody did", async () => {
      // The default has to be the humble one: a component that stays quiet
      // about verification reads as verified.
      const user = userEvent.setup();
      render(<AIDisclosureProvenance claims={claims} />);
      await user.click(screen.getByRole("button", { name: "Content details" }));

      expect(screen.getByText(/Not checked/)).toBeInTheDocument();
      expect(
        screen.getByText(/claims made about the content, not findings/),
      ).toBeInTheDocument();
    });

    it("names who checked, when someone did", async () => {
      const user = userEvent.setup();
      render(<AIDisclosureProvenance claims={claims} source="Acme Trust" verified />);
      await user.click(screen.getByRole("button", { name: "Content details" }));

      expect(
        screen.getByText("Checked by Acme Trust and the claims matched."),
      ).toBeInTheDocument();
    });

    it("reports a failed check as failed rather than as silence", async () => {
      const user = userEvent.setup();
      render(<AIDisclosureProvenance claims={claims} source="Acme Trust" verified={false} />);
      await user.click(screen.getByRole("button", { name: "Content details" }));

      expect(
        screen.getByText("Checked by Acme Trust and the claims did not match."),
      ).toBeInTheDocument();
    });

    it("tells the three states apart in text, not only by colour", async () => {
      const user = userEvent.setup();
      const { rerender } = render(<AIDisclosureProvenance claims={claims} verified />);
      await user.click(screen.getByRole("button", { name: "Content details" }));
      const checked = screen.getByText(/matched/).textContent;

      rerender(<AIDisclosureProvenance claims={claims} verified={false} />);
      const failed = screen.getByText(/did not match/).textContent;

      expect(checked).not.toBe(failed);
    });

    it("marks the status so a caller can style it without re-deriving it", async () => {
      const user = userEvent.setup();
      render(<AIDisclosureProvenance claims={claims} />);
      await user.click(screen.getByRole("button", { name: "Content details" }));

      expect(
        screen
          .getByText(/Not checked/)
          .closest("[data-slot='ai-disclosure-provenance-status']"),
      ).toHaveAttribute("data-status", "unchecked");
    });
  });

  it("names the popover, which carries role=dialog", async () => {
    const user = userEvent.setup();
    render(<AIDisclosureProvenance claims={claims} triggerLabel="Where this came from" />);

    await user.click(screen.getByRole("button", { name: "Where this came from" }));
    expect(screen.getByRole("dialog", { name: "Where this came from" })).toBeInTheDocument();
  });

  it("renders with no claims at all", async () => {
    const user = userEvent.setup();
    render(<AIDisclosureProvenance claims={[]} />);

    await user.click(screen.getByRole("button", { name: "Content details" }));
    expect(screen.getByText(/Not checked/)).toBeInTheDocument();
  });

  it("nests inside a disclosure", async () => {
    const user = userEvent.setup();
    render(
      <AIDisclosure kind="generated">
        <AIDisclosureProvenance claims={claims} />
      </AIDisclosure>,
    );

    expect(screen.getByText("Generated by AI")).toBeInTheDocument();
    await user.click(screen.getByRole("button", { name: "Content details" }));
    expect(screen.getByText("Acme Diffusion 3")).toBeInTheDocument();
  });

  it("has no accessibility violations when open", async () => {
    const user = userEvent.setup();
    const { baseElement } = render(
      <AIDisclosure kind="generated">
        <AIDisclosureProvenance claims={claims} source="Acme Trust" verified />
      </AIDisclosure>,
    );
    await user.click(screen.getByRole("button", { name: "Content details" }));

    await expectNoA11yViolations(baseElement);
  });
});
