export {
  burstFireworks,
  createFireworksShow,
  FIREWORKS,
  FIREWORKS_PALETTE,
  FireworksBackground,
  fireworksBackgroundVariants,
  fireworksSparkAlpha,
  frozenFireworks,
  launchFireworksRocket,
  stepFireworks,
  type FireworksBackgroundProps,
  type FireworksBurstStyle,
  type FireworksFlash,
  type FireworksOptions,
  type FireworksRocket,
  type FireworksShow,
  type FireworksSpark,
  type FireworksStepOptions,
} from "./fireworks-background";
